### PR TITLE
update to prom 1.3

### PR DESCRIPTION
**Pull request by puja108**
this includes a breaking change to K8s SD, need to test

### CODE REVIEW

**Comment by puja108** [comment]
Needs an update to the prom config. However, the changes are not documented in the prom repo or website, yet. Will check (or ask someone) later.

**Comment by puja108** [comment]
update config based on https://prometheus.io/docs/operating/configuration/#<kubernetes_sd_config>

**Comment by puja108** [comment]
WFM (minikube and l8 cluster)

RFR @webwurst (ping @JosephSalisbury just FYI re changes to config)

**Comment by puja108** [comment]
RFR @w0mbat

**Comment by webwurst** [comment]
LGTM

**Comment by w0mbat** [comment]
@puja108 manifests-all is not up-to-date

**Pull request merged**
