### PR TITLE
Provide a quick way to deploy 

### LINKED ISSUE #5: add a quick TLDR way of deploying
For those in a hurry or just wanting to set it up again (like me for the nth time now) it would be cool to have a TLDR way (a script or compressed YAMLs or something) to get to a running state.

What do you think @webwurst ?

### PR DESCRIPTION
**Pull request by webwurst**
Seems to be not that easy to configure datasources or dashboards for Grafana via config files or commandline. It works using the api, although this can only be done after Grafana is running and also needs to deal with authentication.

Workaround for now is done with a Kubernetes job.

Fixes #5

### CODE REVIEW

**Comment by puja108** [comment]
Nice, should we add to README (and maybe docs) that you can run the job instead of going through those manual grafana setup steps?

**Comment by webwurst** [comment]
@puja108 works for me on a fresh minikube. same for you?

**Comment by puja108** [comment]
WFM on a fresh minikube, but the `Prometheus Stats Dashboard` is missing.

Btw, I updated the wording a bit and also added TLDR and `manifests/`-prefix to docs

**Comment by webwurst** [comment]
Right, will add `Prometheus Stats Dashboard` and merge then..

**Pull request merged**
