### PR TITLE
Fix node-exporter image tag

### PR DESCRIPTION
**Pull request by koep**
See https://hub.docker.com/r/prom/node-exporter/tags/

### CODE REVIEW

**Comment by koep** [comment]
ping @puja108

**Comment by puja108** [comment]
LGTM, sorry it took a while was at KubeCon last week ;)

**Comment by koep** [comment]
I know @puja108  - we met ;-)

**Comment by puja108** [comment]
haha, right, these offline-online switches are so confusing ;)

**Pull request merged**
